### ISSUE TITLE
Can't connect to mongo db

### ISSUE THREAD

**Issue by HelloJyo** [proarchgithub/msbotframework-mongo-middlelayer#10]
When I tried to connect, below error message shown.
I think need to add an option { useNewUrlParser: true } when connecting.

(node:22595) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(node:22595) UnhandledPromiseRejectionWarning: Error: Can't connect to db MongoError: Authentication failed.

**Comment by aakashkag** [comment]
I can't reproduce it. May be issue with Mongo server.
